name: deployer-test
on:
    pull_request: null
    push:
        branches:
            - master
    schedule:
        -
            cron: '*/31 14 * * 6'
jobs:
    production:
        runs-on: ubuntu-latest
        name: production deployer end-to-end test
        steps:
            -
                name: production
                id: production
                uses: mshanemc/deployer-check-javascript-action@master
    prerelease:
        runs-on: ubuntu-latest
        name: prerelease deployer end-to-end test
        steps:
            -
                name: prerelease
                id: prerelease
                uses: mshanemc/deployer-check-javascript-action@master
                with:
                    deployer-url: 'https://deployer-prerelease.herokuapp.com'
